SELECT* FROM COUNTRY;
SELECT* FROM CORONAVIRUS_CASES;

SELECT COUNTRY.COUNTRYCODE, COUNTRY.COUNTRYNAME, CORONAVIRUS_CASES.DATE FROM COUNTRY, CORONAVIRUS_CASES
WHERE COUNTRY.COUNTRYCODE = 'PH' AND 
		CORONAVIRUS_CASES.TOTAL_CASES = (SELECT MAX(CORONAVIRUS_CASES.Total_cases)  FROM COUNTRY, CORONAVIRUS_CASES
		WHERE CORONAVIRUS_CASES.COUNTRYCODE = COUNTRY.COUNTRYCODE AND CORONAVIRUS_CASES.COUNTRYCODE = 'PH');
		
SELECT SUM(CORONAVIRUS_CASES.TOTAL_CASES) AS "TOTAL CASES OF INDONESIA FROM 15/03/2020 TO 24/03/2020" FROM CORONAVIRUS_CASES
INNER JOIN COUNTRY ON COUNTRY.COUNTRYCODE = CORONAVIRUS_CASES.COUNTRYCODE
WHERE COUNTRY.COUNTRYCODE = 'ID';

SELECT CORONAVIRUS_CASES.COUNTRYCODE, CORONAVIRUS_CASES.DATE FROM CORONAVIRUS_CASES
WHERE CORONAVIRUS_CASES.COUNTRYCODE = 'ID' AND CORONAVIRUS_CASES.NEW_DEATHS = 0;